# Writes the game's generated data modules from the art and recipe sources.
#   python3 game/tools/gen_data.py
# Inputs:  game/tools/modeldata.json (from art/factorykit.py -- gamedata),
#          art/catalog/blocks.json (from art/blocks.py), data/recipes.json (from data/recipes.py)
# Outputs: game/src/shared/Defs.luau, Recipes.luau, ModelPalette.luau, Models/*.luau
import json, math, os, shutil

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
SHARED = os.path.join(os.path.dirname(HERE), "src", "shared")
models = json.load(open(os.path.join(HERE, "modeldata.json"), encoding="utf-8"))
blocks = json.load(open(os.path.join(ROOT, "art", "catalog", "blocks.json"), encoding="utf-8"))
recipes = json.load(open(os.path.join(ROOT, "data", "recipes.json"), encoding="utf-8"))
HEADER = "-- Generated by game/tools/gen_data.py. Do not edit by hand.\n"


def lua(value, indent=0):
    """A small Python-to-Luau literal writer."""
    pad = "\t" * (indent + 1)
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(round(value, 3)) if isinstance(value, float) else str(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, (list, tuple)):
        if all(isinstance(v, (int, float, str, bool)) for v in value):
            return "{ " + ", ".join(lua(v) for v in value) + " }" if value else "{}"
        return "{\n" + "".join(f"{pad}{lua(v, indent + 1)},\n" for v in value) + "\t" * indent + "}"
    if isinstance(value, dict):
        if not value:
            return "{}"
        rows = []
        for k, v in value.items():
            name = k if k.isidentifier() else f"[{json.dumps(k, ensure_ascii=False)}]"
            rows.append(f"{pad}{name} = {lua(v, indent + 1)},\n")
        return "{\n" + "".join(rows) + "\t" * indent + "}"
    raise TypeError(type(value))


def rgb(hexcode):
    h = hexcode.lstrip("#")
    return [int(h[i:i + 2], 16) for i in (0, 2, 4)]


palette = [dict(rgb=rgb(p["hex"]), neon=p["neon"]) for p in models["palette"]]

# ---------------------------------------------------------------- what each machine does in the game
process_by_machine = {}
for p in recipes["process"]:
    process_by_machine.setdefault(p["machine"], []).append(
        dict(ins=p["ins"], outs=p["outs"], secs=p["secs"]))
EXTRACTS = {"extractor_fe": "ore_fe", "extractor_coal": "coal", "extractor_cu": "ore_cu",
            "pump": "barrel_water", "pumpjack": "barrel_oil"}
PASS = {"splitter": {}, "merger": {}, "funnel": {"topIntake": True},
        "magsep": {"filter": ["ore_fe", "crushed_fe", "clean_fe", "ingot_fe"]}}
# Not offered in the palette. The seller is here because the design has no on-island selling machine.
# Workbenches and hand stations, and the name recipes know each by.
BENCHES = {"wb_basic": "basic", "wb_tool": "tool", "wb_part": "part", "wb_machine": "machine", "wb_cook": "cook",
           "wb_elec": "elec", "wb_furn": "furn", "wb_all": "all", "hand_furnace": "hand_furnace",
           "campfire": "campfire"}
HIDDEN = {"assembler_n", "crop_wheat_2", "crop_wheat_3", "seller"}
# Everything else that does something. The behaviour names the file in server/machines that runs it.
OTHER = {
    "belt_ramp": ("ramp", {}), "chute": ("chute", {}), "lift": ("lift", {}), "launcher": ("launcher", {}),
    "pusher": ("pusher", {}), "blower": ("blower", {}), "sorter": ("sorter", {}),
    "assembler": ("assembler", {}), "circuit": ("assembler", {}), "manufacturer": ("assembler", {}),
    "logger": ("logger", {}), "harvester": ("harvester", {}), "seeder": ("seeder", {}),
    "sprinkler": ("sprinkler", {}), "vending": ("vending", {}), "chest": ("chest", {"topIntake": True}),
    "sign": ("sign", {"walkThrough": True}),
    "generator": ("power", {"power": "generator"}), "incinerator": ("power", {"power": "incinerator"}),
    "windturbine": ("power", {"power": "wind"}), "solar": ("power", {"power": "solar"}),
    "battery": ("power", {"power": "battery"}), "pole": ("power", {"power": "pole"}),
    "reactor": ("power", {"power": "reactor"}),
}
for kind in ("sensor", "gate", "counter", "switch", "logic", "beacon", "timer"):
    OTHER[kind] = ("signal", {"signal": kind})
NOTES = {"assembler": "주인이 고른 물건을 재료 두 가지로 조립함",
         "circuit": "주인이 고른 회로를 만듦",
         "manufacturer": "주인이 고른 물건을 여러 재료로 조립함"}
RENAME = {"crop_wheat_1": "밀 씨앗 (심기)", "plant_sapling": "묘목 (심기)", "extractor_cu": "추출기 (구리 광맥 핵)"}

machines = {}
for key, m in models["machines"].items():
    behavior = "decor"
    extra = {}
    if key in ("belt", "belt_corner"):
        behavior, extra = "belt", {"shape": "straight" if key == "belt" else "right"}
    elif key in EXTRACTS:
        behavior, extra = "extractor", {"item": EXTRACTS[key]}
    elif key in process_by_machine:
        behavior = "processor"
    elif key in PASS:
        behavior, extra = "passthrough", PASS[key]
    elif key == "storage":
        behavior = "chest"
    elif key in BENCHES:
        behavior, extra = "bench", {"bench": BENCHES[key]}
    elif key in OTHER:
        behavior, extra = OTHER[key][0], dict(OTHER[key][1])
    elif key == "plant_sapling":
        behavior, extra = "sapling", {"needsBelow": ["grass", "dirt"], "walkThrough": True, "cost": "sapling"}
    elif key == "crop_wheat_1":
        behavior, extra = "crop", {"needsBelow": ["farmland"], "walkThrough": True, "cost": "seed",
                                   "stages": ["crop_wheat_1", "crop_wheat_2", "crop_wheat_3"]}
    # Cells are 3 studs tall. A machine keeps every cell it reaches into, so nothing can be built
    # through its top.
    layers = max(1, math.ceil((m["height"] - 0.2) / 3))
    machines[key] = dict(name=RENAME.get(key, m["name"]), family=m["family"], note=NOTES.get(key, m["note"]),
                         sx=m["cells"][0], sz=m["cells"][1], sy=layers, height=m["height"], icon=key,
                         ports=[dict(side=s, kind=k, off=o) for s, k, o in m["ports"]],
                         behavior=behavior, hidden=key in HIDDEN, needsPower=key in recipes["needs_power"],
                         **extra)
# A tree has no model file: its shape is made from a seed when it grows (shared/TreeGen).
machines["tree"] = dict(name="나무", family="식물", note="도끼로 치면 통째로 쓰러져 통나무와 묘목을 줌",
                        sx=1, sz=1, sy=6, height=17, icon="plant_sapling", ports=[], behavior="tree",
                        hidden=True, needsPower=False, cost="sapling")
# belt variants that are not separate catalog models
machines["belt_corner_l"] = dict(machines["belt_corner"], name="코너 벨트 (왼쪽)", shape="left")
machines["belt_corner"]["name"] = "코너 벨트 (오른쪽)"
machines["belt_open"] = dict(machines["belt"], name="열린 벨트", shape="open",
                             note="옆 난간이 없어서 옆에서 굴러 들어온 것도 싣고 감")

items = {key: dict(name=i["name"], category=i["category"], color=palette[i["colour"]]["rgb"],
                   size=[max(i["size"])] * 3 if i["ball"] else i["size"], ball=i["ball"])
         for key, i in models["items"].items()}
for made in EXTRACTS.values():
    assert made in items, f"an extractor makes unknown item {made}"
block_defs = {b["key"]: dict(name=b["ko"], category=b["cat"], color=b["colour"], top=b["top"],
                             transparency=0.45 if b["key"] == "glass" else 0) for b in blocks}
# A block and an item may share an id (a log block, a log item): they are the same thing in two
# forms. A machine id must be unique, because a placed id is looked up as block first, then machine.
clash = set(machines) & (set(block_defs) | set(items))
assert not clash, f"machine ids also used by a block or an item: {clash}"

FAMILY_ORDER = ["운반", "물리 장치", "판단 장치", "공급", "식물", "변환", "조합", "포장·판매", "동력",
                "궁극의 장치", "손 작업", "표시"]
palette_groups = []
block_cats = []
for b in blocks:
    if b["cat"] not in block_cats:
        block_cats.append(b["cat"])
for cat in block_cats:
    palette_groups.append(dict(tab="블록", name=cat, ids=[b["key"] for b in blocks if b["cat"] == cat]))
order = ["belt", "belt_corner", "belt_corner_l", "belt_open"]
for fam in FAMILY_ORDER:
    ids = [k for k in order if machines[k]["family"] == fam]
    ids += [k for k, m in machines.items() if m["family"] == fam and k not in order and not m["hidden"]]
    if ids:
        palette_groups.append(dict(tab="기계", name=fam, ids=ids))
item_cats = []
for i in items.values():
    if i["category"] not in item_cats:
        item_cats.append(i["category"])
for cat in item_cats:
    # "item:" marks an entry that drops loose items instead of placing something
    palette_groups.append(dict(tab="아이템", name=cat,
                               ids=["item:" + k for k, i in items.items() if i["category"] == cat]))

hotbar = ["grass", "stone", "belt", "belt_corner", "extractor_fe", "extractor_coal", "smelter", "storage",
          "plant_sapling"]

defs = HEADER + f'''--!nocheck
-- What exists in the game: blocks, loose items, and machines.
local Defs = {{}}

Defs.Blocks = {lua(block_defs)}

Defs.Items = {lua(items)}

Defs.Machines = {lua(machines)}

-- The creative palette, in the order it is shown. Each group belongs to one of three tabs.
Defs.Tabs = {{ "블록", "기계", "아이템" }}
Defs.Palette = {lua(palette_groups)}

Defs.DefaultHotbar = {lua(hotbar)}

function Defs.isBlock(id)
	return type(id) == "string" and Defs.Blocks[id] ~= nil
end

function Defs.isMachine(id)
	return type(id) == "string" and Defs.Machines[id] ~= nil
end

function Defs.isItem(id)
	return type(id) == "string" and Defs.Items[id] ~= nil
end

function Defs.isPlaceable(id)
	return Defs.isBlock(id) or Defs.isMachine(id)
end

-- Palette and hotbar entries are ids of things to place, or "item:<id>" for loose items to drop.
function Defs.itemOf(entry)
	if type(entry) == "string" and string.sub(entry, 1, 5) == "item:" then
		local id = string.sub(entry, 6)
		return if Defs.Items[id] then id else nil
	end
	return nil
end

function Defs.isEntry(entry)
	return Defs.isPlaceable(entry) or Defs.itemOf(entry) ~= nil
end

function Defs.name(entry)
	local item = Defs.itemOf(entry)
	if item then
		return Defs.Items[item].name
	end
	local def = Defs.Blocks[entry] or Defs.Machines[entry] or Defs.Items[entry]
	return if def then def.name else entry
end

return Defs
'''
open(os.path.join(SHARED, "Defs.luau"), "w", encoding="utf-8").write(defs)

uses_fuel = {k: True for k in recipes["fuel_users"] if k in process_by_machine}
craft = [dict(out=c["out"], n=c["n"], bench=c["bench"], tier=c["tier"], ins=c["ins"]) for c in recipes["craft"]]
# The same work done by hand: at a station, sometimes with a tool, burning fuel at a fire.
hand = []
for p in recipes["process"]:
    if p["hand"]:
        station = BENCHES.get(p["hand"], p["hand"])
        entry = dict(station=station, ins=p["ins"], outs=p["outs"], fuel=p["hand"] in recipes["fuel_users"])
        if p["tool"]:
            entry["tool"] = p["tool"]
        hand.append(entry)
known = set(items) | set(machines) | {"block:" + b for b in block_defs}
for c in craft:
    assert c["out"] in known, f"craft makes unknown thing {c['out']}"
    assert all(k in known for k in c["ins"]), f"craft of {c['out']} uses an unknown thing"
for cost in recipes["upgrades"].values():
    assert all(k in known for k in cost), "an upgrade uses an unknown thing"
rec = HEADER + f'''--!nocheck
-- Processing recipes by machine, and how many smelts one unit of each fuel is worth.
return {{
	byMachine = {lua(process_by_machine, 1)},
	fuel = {lua(recipes["fuel"], 1)},
	usesFuel = {lua(uses_fuel, 1)},
	-- Things made by hand: `bench` is "bag" for anywhere, or a workbench kind with its least tier.
	craft = {lua(craft, 1)},
	-- Machine work done by hand at a station.
	hand = {lua(hand, 1)},
	-- What raising a workbench costs, by "kind:tier".
	upgrades = {lua(recipes["upgrades"], 1)},
}}
'''
open(os.path.join(SHARED, "Recipes.luau"), "w", encoding="utf-8").write(rec)

pal = HEADER + "--!nocheck\n-- Colours used by the generated models: r, g, b, and whether the part glows.\nreturn " + lua(
    [[*p["rgb"], p["neon"]] for p in palette]) + "\n"
open(os.path.join(SHARED, "ModelPalette.luau"), "w", encoding="utf-8").write(pal)

model_dir = os.path.join(SHARED, "Models")
shutil.rmtree(model_dir, ignore_errors=True)
os.makedirs(model_dir)
# Items are stored the same way under "item_<id>", for pictures and for what is held in the hand.
shapes = {key: m["prims"] for key, m in models["machines"].items()}
shapes.update({"item_" + key: i["prims"] for key, i in models["items"].items()})
for key, prims in shapes.items():
    flat = [v for prim in prims for v in prim]
    body = ", ".join(repr(v) if isinstance(v, float) else str(v) for v in flat)
    text = HEADER + ("--!nocheck\n-- 17 numbers per part: shape (0 block, 1 cylinder, 2 ball), size x y z, position x y z,\n"
                     "-- nine rotation values, palette index. Positions are relative to the centre of the\n"
                     "-- machine's footprint, one cell above the ground being y = 1.5.\n") + "return { " + body + " }\n"
    open(os.path.join(model_dir, key + ".luau"), "w", encoding="utf-8").write(text)

# Where the middle of each imported mesh lies, in studs, from the middle of its model's footprint
# on the ground. Written by art/factorykit.py -- meshes.
mesh_info_path = os.path.join(ROOT, "art", "export", "game", "models_info.json")
mesh_info = json.load(open(mesh_info_path)) if os.path.exists(mesh_info_path) else {}
centres = {name: e["center"] for name, e in mesh_info.items() if name[:2] in ("m_", "i_")}
open(os.path.join(SHARED, "MeshInfo.luau"), "w", encoding="utf-8").write(
    HEADER + "--!nocheck\n-- The middle of each real mesh: x, y, z in studs from the middle of the model's footprint on\n"
    "-- the ground. Empty if the meshes have not been exported.\nreturn " + lua(centres) + "\n")

# What each machine does in the game, for the catalogue page to show.
json.dump({k: dict(behavior=m["behavior"], hidden=m["hidden"]) for k, m in machines.items()},
          open(os.path.join(ROOT, "art", "catalog", "game.json"), "w"), ensure_ascii=False, indent=0)

print(f"blocks {len(block_defs)}, items {len(items)}, machines {len(machines)}, models {len(models['machines'])}")
working = sorted(k for k, m in machines.items() if m["behavior"] != "decor" and not m["hidden"])
print("working:", len(working), working)
